apiVersion: v1
kind: Service
metadata:
  name: food-health-backend-service
spec:
  selector:
    app: food-health-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
