apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Database configuration
  DATABASE_URL: postgresql://user:password@db:5432/foodapp
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: foodapp
  DB_PORT: "5432"
  
  # Security
  JWT_SECRET: your-jwt-secret
  
  # Environment
  ENVIRONMENT: development